### ISSUE TITLE
Error "gralloc.msm8916.so"

### ISSUE THREAD

**Issue by AlfredoHernandez** [seamfixng/android-nfiq-calc#1]
I'm trying to use this library, but always I've got the next error:

```
08-30 06:53:37.366 13396-13396/mx.com.sample.nfiqexample E/HAL: load: module=/system/lib/hw/gralloc.msm8916.so
    dlopen failed: cannot locate symbol "_Z18isMacroTileEnabledii" referenced by "gralloc.msm8916.so"...
08-30 06:53:37.366 13396-13396/mx.com.sample.nfiqexample E/GraphicBufferMapper: FATAL: can't find the gralloc module
```

Is this a bug? How can I solve it?

**Comment by theartofnonso** [comment]
Hi @AlfredoHernandez , I would like to find out if the App in which you use this Library, depends on any other Library that may be accessing some low-level code, or are you doing something with C/C++ ?

**Comment by AlfredoHernandez** [comment]
Hi @nonsobiose, that's correct, I'm using it in an app that uses low-level code

**Comment by theartofnonso** [comment]
Ok, is the App crashing on specific devices like those running on 32BIT devices?

**Comment by AlfredoHernandez** [comment]
I'm using a Samnsung A8 to test the app, and it's the only device that I tested my app

**Comment by roberto-xD** [comment]
Hi @nonsobiose I´m also have a error similar, I´m use other Library that uses low-level code. The error I got is: 
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__android_log_write" referenced by "/data/app/com.futronictech-2/lib/arm/libftrScanAPI.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)`  
I think is an error with library "Log"
I hope you can helpme. thanks

**Comment by bendaniel10** [comment]
> Hi @nonsobiose I´m also have a error similar, I´m use other Library that uses low-level code. The error I got is:
> `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__android_log_write" referenced by "/data/app/com.futronictech-2/lib/arm/libftrScanAPI.so"... at java.lang.Runtime.loadLibrary(Runtime.java:372) at java.lang.System.loadLibrary(System.java:1076)`
> I think is an error with library "Log"
> I hope you can helpme. thanks

Hi @roberto-xD, this looks like an error with the implementation of your fingerprint scanner. Did you remember to call `System.loadLibrary()` for your Futronic SDK?

**Comment by bendaniel10** [comment]
> I'm using a Samnsung A8 to test the app, and it's the only device that I tested my app

Hi @AlfredoHernandez, I have experienced this error before. I discovered that it happens whenever I use Realm Database (It has a native library part). It mostly happened on a 32 bit device though. I am still looking for how to resolve it. 

The strange thing is that the error doesn't occur on the 32 bit device if I build a test app with just the NFIQ library as the dependency.

**Comment by roberto-xD** [comment]
> > Hi @nonsobiose I´m also have a error similar, I´m use other Library that uses low-level code. The error I got is:
> > `java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__android_log_write" referenced by "/data/app/com.futronictech-2/lib/arm/libftrScanAPI.so"... at java.lang.Runtime.loadLibrary(Runtime.java:372) at java.lang.System.loadLibrary(System.java:1076)`
> > I think is an error with library "Log"
> > I hope you can helpme. thanks
> 
> Hi @roberto-xD, this looks like an error with the implementation of your fingerprint scanner. Did you remember to call `System.loadLibrary()` for your Futronic SDK?

Hi @bendaniel10 yes, I do the call to `System.loadLibrary()` in Futronic SDK, in fact this Library al ready jet work completly, but if I include the dependency `implementation 'com.github.seamfix11:android-nfiq-calc:1.0.1'` and run the app I have that error when I start the comunication with fingerprint scanner

**Comment by AlfredoHernandez** [comment]
> > I'm using a Samnsung A8 to test the app, and it's the only device that I tested my app
> 
> Hi @AlfredoHernandez, I have experienced this error before. I discovered that it happens whenever I use Realm Database (It has a native library part). It mostly happened on a 32 bit device though. I am still looking for how to resolve it.
> 
> The strange thing is that the error doesn't occur on the 32 bit device if I build a test app with just the NFIQ library as the dependency.

Yes, same problem using Realm, and yes, 32 bits device it doesn't ocurr, a little strange. And like @roberto-xD this error happens when I use `System.loadLibraty()` method to load my fingerprint scanner library that also uses low-level code.

**Comment by bendaniel10** [comment]
> Hi @bendaniel10 yes, I do the call to `System.loadLibrary()` in Futronic SDK, in fact this Library al ready jet work completly, but if I include the dependency `implementation 'com.github.seamfix11:android-nfiq-calc:1.0.1'` and run the app I have that error when I start the comunication with fingerprint scanner

Okay, please could you share the OS version of the device you're developing with. According to this [StackOverflow answer](https://stackoverflow.com/a/27338365/2941291), it could be an issue with the target version that the NFIQ library was built with.

**Comment by roberto-xD** [comment]
> > Hi @bendaniel10 yes, I do the call to `System.loadLibrary()` in Futronic SDK, in fact this Library al ready jet work completly, but if I include the dependency `implementation 'com.github.seamfix11:android-nfiq-calc:1.0.1'` and run the app I have that error when I start the comunication with fingerprint scanner
> 
> Okay, please could you share the OS version of the device you're developing with. According to this [StackOverflow answer](https://stackoverflow.com/a/27338365/2941291), it could be an issue with the target version that the NFIQ library was built with.

Hi @bendaniel10  I´m use tablet lenovo yoga with 6.0.1 android versión

**Comment by sampene** [comment]
@bendaniel10 @roberto-xD any solutions?
